language: node_js
node_js:
 - 12.13.0
addons:
  chrome: stable
install:
 - npm install
script:
 - npm run lint
 - npm run test -- --watch=false
 - npm run e2e && npm run e2e:docs
 - npm run build:all

# Send coverage data to Coveralls
# after_script: npm run coverage